### ISSUE TITLE
[BUG]Version incompatibility

### ISSUE THREAD

**Issue by meowstatery** [espressif/idf-clion-plugin#5]
I updated Clion from Ver. 2023.1 to ver. 2023.2, and the installed plugin indicated incompatibility.
![p1](https://github.com/espressif/idf-clion-plugin/assets/79510201/b6d3a19d-7178-4260-a8cf-8bfacca347db)

When I uninstall it and try to reinstall, a message is displayed indicating that the installation failed.
![p2](https://github.com/espressif/idf-clion-plugin/assets/79510201/ff83bcf5-73da-44a4-ad1d-ea5e494348a7)

**Comment by alirana01** [comment]
Hi, 
thank you for your patience, seems like you installed a more recent version of CLion as the error message states you need build 231.* or **older**

**Comment by meowstatery** [comment]
> Hi, thank you for your patience, seems like you installed a more recent version of CLion as the error message states you need build 231.* or **older**

I knew, and What I mean is that I want this plugin to be able to adapt the new version of CLion.
Then, when will the plugin be perfected to the level of idf-vscode-plugin?

**Comment by alirana01** [comment]
Hi @MeowStatus,

Thank you for your interest and for bringing up the important point of feature parity with the idf-vscode-plugin. We're genuinely excited about the potential for this CLion plugin and are keen to bring many of the robust features available in our other plugins for Eclipse and VSCode.

That being said, I'd like to set realistic expectations. This CLion plugin is still in its early beta stage (v0.1), and we have multiple active projects that also require our attention. These projects get updated more frequently, which influences the speed at which we can roll out new features for the CLion plugin.

While I can't provide a specific timeline for when the plugin will reach the level of maturity you're asking about, please know that it is on our roadmap. Improvements and additional features will be introduced, but they will come at a gradual pace. Your feedback is incredibly valuable to us, and it helps prioritize what features to work on next.

Thank you for your understanding and for being part of our community. We appreciate your patience as we work to make this plugin as useful as possible.

Best regards,
Ali Azam Rana
